# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eefb3b8cdfbcfa2b6410febb1ef3fcb9d354ce1c26346dfc8fd3acd77b43a8f353b0ade131a1b4a9eed828427fd46cac6ca4abb1cc92b462f6c24cc3855ede7d

test:
  secret_key_base: 981a85b928fbcd533340ba4658614133294bebb00c34ba54f818bdbb994097d541d542e5f2ff36be95d6c7c9153895114e8f149e8020d5871e9ce56cceacc590

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
